language: java

services:
  - docker

before_install:
  - echo Before install
  - docker version

before_script:
  - echo before scripts

script:
  - mvn clean test verify
  - docker build -t joshikeyur/ms-with-kafka .

after_script:
  - echo After scripts