language: java

services:
  - docker

before_install:
  - echo Before install
  - docker version

before_script:
  - echo before scripts

script:
  - mvn clean test verify
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t joshikeyur/ms-with-kafka .
  - docker run --rm -it amazon/aws-cli --version

after_script:
  - echo After scripts