server:
  port: 80
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
   # url: jdbc:mysql://localhost:3306/sampleapp
   # username: root
   # password: lionking1
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
downstream:
  reqres:
    url: https://reqres.in/api/users
  coingecko:
    url: https://api.coingecko.com/api